### ISSUE TITLE
Exception-Code: EPIPE: This socket has been ended by the other party

### ISSUE THREAD

**Issue by marlan99** [XHunter74/ioBroker.apcups#1]
just installed this adapter (V0.0.3) today and works great. thanks

When the default configuration is active there is no problem running the instance.
But when i change the intervall to 30000 (30 sec.) then it crashes regularly with following messages:

`

host.iobroker-slave | 2022-01-12 18:41:44.921 | info | Restart adapter system.adapter.apcups.0 because enabled
-- | -- | -- | --
host.iobroker-slave | 2022-01-12 18:41:44.919 | error | instance system.adapter.apcups.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
apcups.0 | 2022-01-12 18:41:44.317 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
apcups.0 | 2022-01-12 18:41:44.315 | info | terminating
apcups.0 | 2022-01-12 18:41:44.305 | error | Exception-Code: EPIPE: This socket has been ended by the other party
apcups.0 | 2022-01-12 18:41:44.303 | error | Error: This socket has been ended by the other party at Socket.writeAfterFIN [as write] (net.js:468:14) at ApcAccess._flush (/opt/iobroker/node_modules/apcaccess/lib/apcaccess.js:152:18) at /opt/iobroker/node_modules/apcaccess/lib/apcaccess.js:112:10 at new Promise (<anonymous>) at ApcAccess.getStatus (/opt/iobroker/node_modules/apcaccess/lib/apcaccess.js:105:10) at /opt/iobroker/node_modules/apcaccess/lib/apcaccess.js:118:10 at new Promise (<anonymous>) at ApcAccess.getStatusJson (/opt/iobroker/node_modules/apcaccess/lib/apcaccess.js:117:10) at ApcUpsAdapter.processTask (/opt/iobroker/node_modules/iobroker.apcups/main.js:76:35) at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.apcups/main.js:72:56)
apcups.0 | 2022-01-12 18:41:44.299 | error | uncaught exception: This socket has been ended by the other party
apcups.0 | 2022-01-12 18:41:29.309 | info | Disconnected from apcupsd
apcups.0 | 2022-01-12 18:41:14.309 | info | Connected to apcupsd successfully
apcups.0 | 2022-01-12 18:41:14.289 | info | Polling interval: 30000
apcups.0 | 2022-01-12 18:41:14.288 | info | UPS Port: 3551
apcups.0 | 2022-01-12 18:41:14.287 | info | UPS IP: 127.0.0.1

`

**Comment by XHunter74** [comment]
Actually, I did not expect that apcupsd will close the connection after 15 sec. Now issue should be fixed.

**Comment by marlan99** [comment]
cool ! 
Its working now. thx

will close the issue now
