### ISSUE TITLE
Please consider fixing issues reported by adapter checker

### ISSUE THREAD

**Issue by mcm1957** [XHunter74/ioBroker.apcups#15]
👀 [W184] "common.main" is deprecated and ignored. Please remove from [io-package.json](https://github.com/XHunter74/ioBroker.apcups/blob/master/io-package.json). Use "main" at [package.json](https://github.com/XHunter74/ioBroker.apcups/blob/master/package.json) instead.
 👀 [W184] "common.materialize" is deprecated for admin >= 5 at [io-package.json](https://github.com/XHunter74/ioBroker.apcups/blob/master/io-package.json). Please use property "adminUI".
 👀 [W184] "common.title" is deprecated and replaced by "common.titleLang". Please remove from [io-package.json](https://github.com/XHunter74/ioBroker.apcups/blob/master/io-package.json).

**Comment by XHunter74** [comment]
Already fixed

**Comment by mcm1957** [comment]
Thanks
