### ISSUE TITLE
Battery Change Date

### ISSUE THREAD

**Issue by fritz47110815** [XHunter74/ioBroker.apcups#5]
My UPS provides the BATTDATE parameter, which is the change date of the battery. Is it possible to add it?

**Comment by XHunter74** [comment]
will see on it

**Comment by fritz47110815** [comment]
Wow - you are fast. Thanks a lot!
Just one point: after downloading the new version I had to delete and recreate the instance, because the new data point has not been created by a simple restart. Is there an easy solution?

**Comment by XHunter74** [comment]
you should wait for version 1.0.13. Will be available from npm today or tomorrow.
