### ISSUE TITLE
Adapter does not create any values

### ISSUE THREAD

**Issue by ChrMaass** [XHunter74/ioBroker.apcups#6]
After I installed and configured the adapter, it successfully connects to the APC UPS server. In the DEBUG output, I can see the values received and thus the UPS connected to the server. So far everything looks correct...

Unfortunately, the adapter does not create any objects for me. Only the three info values (Host, Port and Connected = true) are displayed. The values of the UPS are not visible. 

What am I doing wrong? Or is it a known bug?

**Comment by ChrMaass** [comment]
<img width="1254" alt="image" src="https://user-images.githubusercontent.com/47745022/234099902-884dec10-aa55-4da3-84bd-050745c7ffb8.png">

**Comment by ChrMaass** [comment]
apcups.0 | 2023-04-24 21:40:26.600 | debug | Disconnected from apcupsd '192.168.55.250:3551'
-- | -- | -- | --
apcups.0 | 2023-04-24 21:40:26.520 | debug | UPS state: '{"APC":"001,036,0859","DATE":"2023-04-24T21:39:32+02:00","HOSTNAME":"proxmox","VERSION":"3.14.14 (31 May 2016) debian","UPSNAME":"garage","CABLE":"USB Cable","DRIVER":"USB UPS Driver","UPSMODE":"Stand Alone","STARTTIME":"2023-04-24T21:10:27+02:00","MODEL":"Back-UPS RS 1300MI ","STATUS":"ONLINE ","LINEV":233,"LOADPCT":12,"BCHARGE":100,"TIMELEFT":45.9,"MBATTCHG":10,"MINTIMEL":8,"MAXTIME":0,"SENSE":"Medium","LOTRANS":176,"HITRANS":288,"ALARMDEL":"30 Seconds","BATTV":27.3,"LASTXFER":"Low line voltage","NUMXFERS":0,"TONBATT":0,"CUMONBATT":0,"XOFFBATT":"NaN-NaN-NaNTNaN:NaN:NaN-NaN:NaN","SELFTEST":"NO","STATFLAG":"0x05000008","SERIALNO":"5B2203T48900 ","BATTDATE":"2022-01-21","NOMINV":230,"NOMBATTV":24,"NOMPOWER":780,"FIRMWARE":"949.g3 .I USB FW:g3","ENDAPC":"2023-04-24T21:40:26+02:00"}'
apcups.0 | 2023-04-24 21:40:26.517 | debug | Connected to apcupsd '192.168.55.250:3551' successfully

**Comment by XHunter74** [comment]
Strange situation. Will investigate

**Comment by ChrMaass** [comment]
I have now completely deleted it again and installed it fresh, directly with the version from Github. Now the objects have been created. I suspect it was the version 1.0.12 in between that caused a problem.
